apiVersion: v1
kind: Service
metadata:
  name: demo-webapp-svc
  labels:
    app: demo-webapp-svc
  namespace: demo-webapp 
spec:
  type: NodePort
  selector:
    app: demo-webapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80